### PR TITLE
cran fixes

### PR DESCRIPTION
**Pull request by alkaZeltser**
Fixes for the following notes reported by first CRAN submission attempt:

```
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
Check: DESCRIPTION meta-information, Result: NOTE
  Authors@R field gives persons with invalid ORCID identifiers:
    Nicole Zeltser [aut] (000-0001-7246-2771)

Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
Check: S3 generic/method consistency, Result: NOTE
  Mismatches for apparent methods not registered:
  merge:
    function(x, y, ...)
  merge.pgs.bed:
    function(pgs.bed.list, add.annotation.data, annotation.column.index,
             slop)
  
  merge:
    function(x, y, ...)
  merge.vcf.with.pgs:
    function(vcf.data, pgs.weight.data)
  See section 'Registering S3 methods' in the 'Writing R Extensions'
  manual.

Flavor: r-devel-windows-x86_64
Check: examples, Result: NOTE
  Examples with CPU (user + system) or elapsed time > 10s
                                             user system elapsed
  create.pgs.density.plot                   10.85   2.53   14.27
  create.pgs.with.continuous.phenotype.plot  7.85   2.47   11.05

Flavor: r-devel-linux-x86_64-debian-gcc
Check: examples, Result: NOTE
  Examples with CPU (user + system) or elapsed time > 5s
                                              user system elapsed
  create.pgs.density.plot                   16.605  0.582  17.777
  create.pgs.with.continuous.phenotype.plot 11.307  0.361  11.663

```

- [x] I have read the [code review guidelines](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3187646/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [x] The name of the branch is meaningful and well formatted following the [standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List), using \[AD_username (or 5 letters of AD if AD is too long)-\[brief_description_of_branch].

- [x] I have set up or verified the branch protection rule following the [github standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3190380/GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.

- [x] I have added the changes included in this pull request to `NEWS` under the next release version or unreleased, and updated the date.

- [ ] I have updated the version number in `metadata.yaml` and `DESCRIPTION`.

- [ ] Both `R CMD build` and `R CMD check` run successfully.

Closes #...

## Testing Results

All unit tests pass

### CODE REVIEW

**Comment by alkaZeltser** [comment]
@dan-knight any thoughts on how to version the next (patch?) release prior to the next CRAN submission attempt? There is a breaking change in this PR.

**Review by forbiddenpersimmon — APPROVED** [review]
Fixes to ORCID ID and changes from `merge.` to `combine.` to address CRAN notes LGTM!

**Comment by alkaZeltser** [comment]
FYI logs from the win-builder R validation server for this version are temporary available for view here:
https://win-builder.r-project.org/jUQWchLIV5Pf/

Looks like all previous NOTES resolved, except for a spelling issue that we will try to appeal.

**Comment by dan-knight** [comment]
Looks good to me! Just one thing:

There's some subjectivity with the use of `\donttest`. Did you get any feedback on this from @pboutros? In theory, a package should be able to have small examples that fully demonstrate the package's functionality without taking long to run. However, this may not always be possible. Then, there's a tradeoff between the benefits of running a more minimal (maybe worse) example and not running a more ideal example. If you don't think that this is exposing a performance issue in your functionality or example code, then I think it's reasonable to use `\donttest`.  (In other words, if this speed issue isn't addressable on your end.)

**Comment by alkaZeltser** [comment]
> Looks good to me! Just one thing:
> 
> There's some subjectivity with the use of `\donttest`. Did you get any feedback on this from @pboutros? In theory, a package should be able to have small examples that fully demonstrate the package's functionality without taking long to run. However, this may not always be possible. Then, there's a tradeoff between the benefits of running a more minimal (maybe worse) example and not running a more ideal example. If you don't think that this is exposing a performance issue in your functionality or example code, then I think it's reasonable to use `\donttest`. (In other words, if this speed issue isn't addressable on your end.)

I agree that small functional examples are a good goal. If you take a look at what I've done, in both functions that were exceeding the runtime limit, I have applied \donttest{} to all **but one** of the examples in each function. Both of these functions are producing multipanel plots in 4-5 examples -> this is one of the main causes that is ballooning the runtime. Five complex multipanels rendered! It's a lot. I have kept one basic example untouched, per the philosophy you stated, and excluded the rest.

I think that is quite reasonable. @pboutros would be glad to hear your thoughts.

**Comment by dan-knight** [comment]
> Both of these functions are producing multipanel plots in 4-5 examples -> this is one of the main causes that is ballooning the runtime. Five complex multipanels rendered! It's a lot. I have kept one basic example untouched, per the philosophy you stated, and excluded the rest.
> 
> I think that is quite reasonable.

Yep! Sounds fine to me. Graphics are tough overall, and the runtime seems to be happening during the calls to BPG rather than your code. We took a look at your data prep and code around the BPG functions, and nothing jumped out to me as a performance issue.

You always have the option to run the excluded examples with the `--run-donttest` flag. I'd recommend that as you're making changes just to be sure. We should probably add that to our CI/CD action too, as it's definitely worth the extra few seconds for us to get better feedback during development. I'll make a note of this.

**Review by dan-knight — APPROVED** [review]

**Comment by alkaZeltser** [comment]
> You always have the option to run the excluded examples with the `--run-donttest` flag. I'd recommend that as you're making changes just to be sure. We should probably add that to our CI/CD action too, as it's definitely worth the extra few seconds for us to get better feedback during development. I'll make a note of this.

Happily, I have noted that R CMD Check does this automatically!

```
✔  checking files in ‘vignettes’ ...
─  checking examples ... [12s/13s] OK (13s)
─  checking examples with --run-donttest ... [39s/39s] OK (39.5s)
```

**Comment by dan-knight** [comment]
> Happily, I have noted that R CMD Check does this automatically!

Great. `\donttest` is the right choice over `\dontrun`.

**Comment by dan-knight** [comment]
> any thoughts on how to version the next (patch?) release prior to the next CRAN submission attempt? There is a breaking change in this PR.

Yeah, (annoyingly) it should technically be `v2.0.0`. These are _technically_ breaking public functions. You could make an argument for `v1.0.1` since `v1.0.0` was a bit like a pre-release version, but it's probably not worth it.

Here are a few thoughts on the matter from @aholmes:
>i think it should be bumped to v2.0.0. some things to consider:
> - major version number isn't something to fret over - it's just a signifier of what it means. "major" is kind of a misnomer
> - it's not uncommon to publicly release software that has jumped several numbers because of things like internal releases
> - because each number has a specific meaning, if someone were to use v1.0.0 for any reason (like, internal to the lab since it's not released) and then wanted to update, it would break them
> - it's much easier just to let the idea of "major" go than it is to deal with any possible fallout of not following semver

**Comment by alkaZeltser** [comment]
> > any thoughts on how to version the next (patch?) release prior to the next CRAN submission attempt? There is a breaking change in this PR.
> 
> Yeah, (annoyingly) it should technically be `v2.0.0`. These are _technically_ breaking public functions. You could make an argument for `v1.0.1` since `v1.0.0` was a bit like a pre-release version, but it's probably not worth it.

Happy with v2.0.0 and got approval from Paul on this and `\donttest{}` implementation. I'll go ahead and merge this and start a v2.0.0 release PR, then we can upload this thing again :)

**Pull request merged**
